version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 0"
  - dependency-name: setuptools
    versions:
    - ">= 0"
  - dependency-name: twine
    versions:
    - ">= 0"
  - dependency-name: wheel
    versions:
    - ">= 0"
  - dependency-name: honeybee-radiance
    versions:
    - 1.29.10
    - 1.29.11
    - 1.29.12
    - 1.29.13
    - 1.29.8
    - 1.30.0
    - 1.30.1
    - 1.31.0
    - 1.31.1
    - 1.32.0
    - 1.33.0
    - 1.33.1
    - 1.33.2
    - 1.34.0
    - 1.35.0
  - dependency-name: pollination-dsl
    versions:
    - 0.8.8
  - dependency-name: queenbee-dsl
    versions:
    - 0.7.2
